//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeCinemaManufacturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HomeCinemaManufacturer()
        {
            this.HomeCinemaSpecification = new HashSet<HomeCinemaSpecification>();
        }
    
        public int id { get; set; }
        public string manufacturer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeCinemaSpecification> HomeCinemaSpecification { get; set; }
    }
}
