//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeCinemaSpecification
    {
        public int id { get; set; }
        public int idManufacturer { get; set; }
        public string permission { get; set; }
        public int brightness { get; set; }
        public int contrast { get; set; }
    
        public virtual HomeCinemaManufacturer HomeCinemaManufacturer { get; set; }
    }
}
